version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network


  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis-exporter
    environment:
      REDIS_ADDR: "redis:6379"
      REDIS_EXPORTER_INCL_SYSTEM_METRICS: "true"
      REDIS_EXPORTER_INCL_COMMANDS: "true"
    ports:
      - "9121:9121"
    networks:
      - app_network


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - app_network

  app:
    build: .
    container_name: go-api
    ports:
      - "3000:3000"
    environment:
      - REDIS_ADDR=redis:6379  # Redis'in adresi
    depends_on:
      - redis
    networks:
      - app_network


networks:
  app_network:
    driver: bridge