scrape_configs:
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'redis_.*'
        action: keep

  - job_name: 'rate-limiter'
    static_configs:
      - targets: ['go-api:3000']  # Fiber API uygulamasını izleyelim
